// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: meru.proto

package merupb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MeruNode_Ping_FullMethodName         = "/conductor.MeruNode/Ping"
	MeruNode_Spawn_FullMethodName        = "/conductor.MeruNode/Spawn"
	MeruNode_Send_FullMethodName         = "/conductor.MeruNode/Send"
	MeruNode_Stop_FullMethodName         = "/conductor.MeruNode/Stop"
	MeruNode_GetSession_FullMethodName   = "/conductor.MeruNode/GetSession"
	MeruNode_ListSessions_FullMethodName = "/conductor.MeruNode/ListSessions"
	MeruNode_GetLogs_FullMethodName      = "/conductor.MeruNode/GetLogs"
	MeruNode_ListDir_FullMethodName      = "/conductor.MeruNode/ListDir"
	MeruNode_GitClone_FullMethodName     = "/conductor.MeruNode/GitClone"
)

// MeruNodeClient is the client API for MeruNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MeruNode is the service exposed by each remote agent node.
// The control-plane (local Conductor daemon) is the only client.
type MeruNodeClient interface {
	// Ping checks connectivity and returns node capabilities.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// Spawn creates a new agent session on the remote node.
	// The control plane provides the session ID so it can reconnect after restart.
	Spawn(ctx context.Context, in *SpawnRequest, opts ...grpc.CallOption) (*SpawnResponse, error)
	// Send delivers a prompt to a session and streams events back.
	Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EventMessage], error)
	// Stop terminates a session on the remote node.
	Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error)
	// GetSession returns the current state of a session.
	GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*SessionInfo, error)
	// ListSessions returns all sessions known to the remote node.
	ListSessions(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListSessionsResponse, error)
	// GetLogs returns historical events for a session.
	GetLogs(ctx context.Context, in *GetLogsRequest, opts ...grpc.CallOption) (*GetLogsResponse, error)
	// ListDir returns the entries of a directory on the remote node's filesystem.
	ListDir(ctx context.Context, in *ListDirRequest, opts ...grpc.CallOption) (*ListDirResponse, error)
	// GitClone clones a git repository on the remote node.
	GitClone(ctx context.Context, in *GitCloneRequest, opts ...grpc.CallOption) (*GitCloneResponse, error)
}

type meruNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewMeruNodeClient(cc grpc.ClientConnInterface) MeruNodeClient {
	return &meruNodeClient{cc}
}

func (c *meruNodeClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, MeruNode_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meruNodeClient) Spawn(ctx context.Context, in *SpawnRequest, opts ...grpc.CallOption) (*SpawnResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SpawnResponse)
	err := c.cc.Invoke(ctx, MeruNode_Spawn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meruNodeClient) Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EventMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MeruNode_ServiceDesc.Streams[0], MeruNode_Send_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SendRequest, EventMessage]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MeruNode_SendClient = grpc.ServerStreamingClient[EventMessage]

func (c *meruNodeClient) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopResponse)
	err := c.cc.Invoke(ctx, MeruNode_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meruNodeClient) GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*SessionInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionInfo)
	err := c.cc.Invoke(ctx, MeruNode_GetSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meruNodeClient) ListSessions(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionsResponse)
	err := c.cc.Invoke(ctx, MeruNode_ListSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meruNodeClient) GetLogs(ctx context.Context, in *GetLogsRequest, opts ...grpc.CallOption) (*GetLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLogsResponse)
	err := c.cc.Invoke(ctx, MeruNode_GetLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meruNodeClient) ListDir(ctx context.Context, in *ListDirRequest, opts ...grpc.CallOption) (*ListDirResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDirResponse)
	err := c.cc.Invoke(ctx, MeruNode_ListDir_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meruNodeClient) GitClone(ctx context.Context, in *GitCloneRequest, opts ...grpc.CallOption) (*GitCloneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GitCloneResponse)
	err := c.cc.Invoke(ctx, MeruNode_GitClone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MeruNodeServer is the server API for MeruNode service.
// All implementations must embed UnimplementedMeruNodeServer
// for forward compatibility.
//
// MeruNode is the service exposed by each remote agent node.
// The control-plane (local Conductor daemon) is the only client.
type MeruNodeServer interface {
	// Ping checks connectivity and returns node capabilities.
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// Spawn creates a new agent session on the remote node.
	// The control plane provides the session ID so it can reconnect after restart.
	Spawn(context.Context, *SpawnRequest) (*SpawnResponse, error)
	// Send delivers a prompt to a session and streams events back.
	Send(*SendRequest, grpc.ServerStreamingServer[EventMessage]) error
	// Stop terminates a session on the remote node.
	Stop(context.Context, *StopRequest) (*StopResponse, error)
	// GetSession returns the current state of a session.
	GetSession(context.Context, *GetSessionRequest) (*SessionInfo, error)
	// ListSessions returns all sessions known to the remote node.
	ListSessions(context.Context, *Empty) (*ListSessionsResponse, error)
	// GetLogs returns historical events for a session.
	GetLogs(context.Context, *GetLogsRequest) (*GetLogsResponse, error)
	// ListDir returns the entries of a directory on the remote node's filesystem.
	ListDir(context.Context, *ListDirRequest) (*ListDirResponse, error)
	// GitClone clones a git repository on the remote node.
	GitClone(context.Context, *GitCloneRequest) (*GitCloneResponse, error)
	mustEmbedUnimplementedMeruNodeServer()
}

// UnimplementedMeruNodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMeruNodeServer struct{}

func (UnimplementedMeruNodeServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedMeruNodeServer) Spawn(context.Context, *SpawnRequest) (*SpawnResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Spawn not implemented")
}
func (UnimplementedMeruNodeServer) Send(*SendRequest, grpc.ServerStreamingServer[EventMessage]) error {
	return status.Error(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedMeruNodeServer) Stop(context.Context, *StopRequest) (*StopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedMeruNodeServer) GetSession(context.Context, *GetSessionRequest) (*SessionInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSession not implemented")
}
func (UnimplementedMeruNodeServer) ListSessions(context.Context, *Empty) (*ListSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedMeruNodeServer) GetLogs(context.Context, *GetLogsRequest) (*GetLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLogs not implemented")
}
func (UnimplementedMeruNodeServer) ListDir(context.Context, *ListDirRequest) (*ListDirResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDir not implemented")
}
func (UnimplementedMeruNodeServer) GitClone(context.Context, *GitCloneRequest) (*GitCloneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GitClone not implemented")
}
func (UnimplementedMeruNodeServer) mustEmbedUnimplementedMeruNodeServer() {}
func (UnimplementedMeruNodeServer) testEmbeddedByValue()                       {}

// UnsafeMeruNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MeruNodeServer will
// result in compilation errors.
type UnsafeMeruNodeServer interface {
	mustEmbedUnimplementedMeruNodeServer()
}

func RegisterMeruNodeServer(s grpc.ServiceRegistrar, srv MeruNodeServer) {
	// If the following call panics, it indicates UnimplementedMeruNodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MeruNode_ServiceDesc, srv)
}

func _MeruNode_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeruNodeServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeruNode_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeruNodeServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeruNode_Spawn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpawnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeruNodeServer).Spawn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeruNode_Spawn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeruNodeServer).Spawn(ctx, req.(*SpawnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeruNode_Send_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SendRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MeruNodeServer).Send(m, &grpc.GenericServerStream[SendRequest, EventMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MeruNode_SendServer = grpc.ServerStreamingServer[EventMessage]

func _MeruNode_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeruNodeServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeruNode_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeruNodeServer).Stop(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeruNode_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeruNodeServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeruNode_GetSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeruNodeServer).GetSession(ctx, req.(*GetSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeruNode_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeruNodeServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeruNode_ListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeruNodeServer).ListSessions(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeruNode_GetLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeruNodeServer).GetLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeruNode_GetLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeruNodeServer).GetLogs(ctx, req.(*GetLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeruNode_ListDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeruNodeServer).ListDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeruNode_ListDir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeruNodeServer).ListDir(ctx, req.(*ListDirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeruNode_GitClone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GitCloneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeruNodeServer).GitClone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeruNode_GitClone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeruNodeServer).GitClone(ctx, req.(*GitCloneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MeruNode_ServiceDesc is the grpc.ServiceDesc for MeruNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MeruNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "conductor.MeruNode",
	HandlerType: (*MeruNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _MeruNode_Ping_Handler,
		},
		{
			MethodName: "Spawn",
			Handler:    _MeruNode_Spawn_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _MeruNode_Stop_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _MeruNode_GetSession_Handler,
		},
		{
			MethodName: "ListSessions",
			Handler:    _MeruNode_ListSessions_Handler,
		},
		{
			MethodName: "GetLogs",
			Handler:    _MeruNode_GetLogs_Handler,
		},
		{
			MethodName: "ListDir",
			Handler:    _MeruNode_ListDir_Handler,
		},
		{
			MethodName: "GitClone",
			Handler:    _MeruNode_GitClone_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Send",
			Handler:       _MeruNode_Send_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "conductor.proto",
}
